package com.thoughtworks.cyclerental.service;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.thoughtworks.cyclerental.dto.Customer;
import com.thoughtworks.cyclerental.dto.Customers;
import com.thoughtworks.cyclerental.dto.Cycle;
import com.thoughtworks.cyclerental.dto.Cycles;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;


import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.assertEquals;

public class RentalServiceTest {

    @Test public void testSomeLibraryMethod() {
        //Query: While refactoring I had to change the initialisation,
        // will it not break any code in production ?

        Cycles cycleList = new Cycles();
        Customers customerList = new Customers();

        Customer customer1 = new Customer(1, "Swetha");
//        Customer customer2 = new Customer(1, "Sravya");
        Cycle cycle1 = new Cycle(1, "LB", "Hero", 10.0, 4, 5.0);
//        Cycle cycle2 = new Cycle(2, "LB", "Hero", 30.0);
//        Cycle cycle3 = new Cycle(3, "LB", "Hero", 20.0);

        cycleList.add(cycle1);
//        cycleList.add(cycle2);
//        cycleList.add(cycle3);

        customerList.add(customer1);
//        customerList.add(customer2);

        RentalService rentalService = new RentalService(cycleList, customerList);

        rentalService.rentCycle(1, 1);

        String returnCycle = rentalService.returnCycle(1, 4);

        assertEquals("4 Rent: 10.0\n" +
                "-------------------------------------------\n" +
                "Total: 10.0", returnCycle);
    }

    @After
    public void tearDown() throws Exception {
    }

    @Before
    public void setUp() throws Exception {
    }
}
