package com.thoughtworks.cyclerental.service;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class RentalServiceTest {

    @Test public void testSomeLibraryMethod() {
        assertEquals("1","1");
    }

    @After
    public void tearDown() throws Exception {
    }

    @Before
    public void setUp() throws Exception {
    }
}
